# Maintainer: Jere Hasu
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=picmaker-bin
pkgver=0.1.1
pkgrel=1
pkgdesc="Makes arduino instructions from svg files"
url="https://wiki.aalto.fi/pages/viewpage.action?pageId=234042176"
license=("GPL-3.0-or-later")
arch=("x86_64")
provides=("picmaker")
conflicts=("picmaker")
source=("https://github.com/Sahkopaja-ryhma-21/picmaker/releases/download/v$pkgver/picmaker-$pkgver-x86_64.tar.gz")
sha256sums=("0ba976ca77c75fae6eaee203a29c6c3f2f7de9d38296af74fec6ed670c4c5a83")

package() {
    install -Dm755 picmaker -t "$pkgdir/usr/bin"
}
